#app
server:
    port: 8081

#spring
spring:
  profiles:
    active: prod
#热加载
  devtools:
    restart:
      enabled: false
  datasource:
      dynamic:
        primary: master #设置默认的数据源或者数据源组,默认值即为master
        datasource:
          master:
            username: guozg
            password: guozg
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://47.100.99.68:3306/guozg?useUnicode=true&characterEncoding=utf8
          slave_1:
            username: root
            password: root
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://127.0.0.1:3306/guozg?useUnicode=true&characterEncoding=utf8
  redis:
      database: 0
      host: 47.100.99.68
      port: 6379
      password:
      pool:
        max:
          active: 8
          wait: -1
          idle: 8
        min:
          idle: 0
      timeout: 5000

#database
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.100.99.68:3306/guozg?useUnicode=true&characterEncoding=utf8
#   username: guozg
#   password: guozg

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.gzg.*.entity
  #开启日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 数据库相关配置
        db-config:
          #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
          id-type: INPUT
          #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
          field-strategy: not_empty
          #驼峰下划线转换
          column-underline: true
          #数据库大写下划线转换
          #capital-mode: true
          #逻辑删除配置
          logic-delete-value: 1
          logic-not-delete-value: 0
          db-type: mysql
        #刷新mapper 调试神器
        refresh: true